### ISSUE TITLE
Boilerplate for React

### ISSUE THREAD

**Issue by shreyas44** [alhassanv/boilerplate#5]
Create a boilerplate for React (not using `create-react-app`) including a webpack config (with a dev server) and a babel config

**Comment by alhassanv** [comment]
Would you like to be assigned?

**Comment by shreyas44** [comment]
@alhassanv yup!

**Comment by alhassanv** [comment]
> @alhassanv yup!

I have assigned you!

**Comment by alhassanv** [comment]
> @alhassanv yup!

Any update? @shreyas44

**Comment by shreyas44** [comment]
@alhassanv Sorry, wasn't able to work on it, will work on it today and submit a PR tomorrow

**Comment by alhassanv** [comment]
@shreyas44 Please let me know if you are going to do this, otherwise I will close this issue.

**Comment by shreyas44** [comment]
@alhassanv over the last few weeks I've explored React frameworks such as Gatsby and Nextjs and looking at what they offer, it seems like a much better option to just go ahead and use one of them rather than use any React boilerplate code or even `create-react-app`

**Comment by alhassanv** [comment]
@shreyas44 Closing this issue in 12 hours if you dont PR anything.
