### ISSUE TITLE
Boilerplate for Python

### ISSUE THREAD

**Issue by Vyvy-vi** [alhassanv/boilerplate#6]
Also, can you kinda explain the project.
Like, do I translate the js version into python, right?

**Comment by Vyvy-vi** [comment]
or you mean the literal sense of the word 'boilerplate'

**Comment by alhassanv** [comment]
@Vyvy-vi By boilerplate I mean the basic stuff used to run a bot for python it's cogs I think.

**Comment by Vyvy-vi** [comment]
Ok will do
___The basic stuff needed to run is 2 import commands and a function call___

**Comment by Vyvy-vi** [comment]
I'll just add a modularised code with basic commands included (help etc)

**Comment by alhassanv** [comment]
> I'll just add a modularised code with basic commands included (help etc)

Yep that works!

**Comment by Vyvy-vi** [comment]
didn't add a help command as discord.py contains one by default
